name: Build HDRScreenSaver

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.25.0'
    
    - name: Set up Visual Studio
      uses: microsoft/setup-msbuild@v1.3.1
    
    - name: Configure CMake
      run: cmake -S . -B build -G "Visual Studio 17 2022" -A x64
      env:
        XMP_TOOLKIT_DIR: ${{ github.workspace }}/XMP-Toolkit-SDK
    
    - name: Build
      run: cmake --build build --config Release
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: HDRScreenSaver-build
        path: build/Release/*.scr
        retention-days: 7 